#Dev
-
  shallow_clone: true
  branches:
    only:
      - develop
  init:
    - echo Init Dev
  build_script:
    - echo Building dev...
  test_script:
    - echo Testing dev...
  notifications:
    provider: Webhook
    method: GET
    url: https://shrouded-fjord-84247.herokuapp.com/deployment?project={{build.projectName}}&buildno={{build.buildNumber}}&env=dev

#Staging
-
  shallow_clone: true
  branches:
    only:
      - staging
  init:
    - echo Init Staging
  build_script:
    - echo Building staging...
  test_script:
    - echo Testing staging...
  notifications:
    provider: Webhook
    method: GET
    url: https://shrouded-fjord-84247.herokuapp.com/deployment?project={{build.projectName}}&buildno={{build.buildNumber}}&env=staging

#Prod
-
  shallow_clone: true
  branches:
    only:
      - master
  init:
    - echo Init Productions
  build_script:
    - echo Building production...
  test_script:
    - echo Testing production...
  notifications:
    provider: Webhook
    method: GET
    url: https://shrouded-fjord-84247.herokuapp.com/deployment?project={{build.projectName}}&buildno={{build.buildNumber}}&env=production

